apiVersion: apps/v1

kind: Deployment

metadata:

  name: jenkins
  
spec:

  selector:
  
    matchLabels:
    
      run: jenkins
      
  replicas: 1
  
  template:
    
    metadata:
    
      labels:
      
        run: jenkins
        
    spec:
      
      containers:
      
      - name: jenkins
      
        image: anandsadhu/dotnet-jenkins-slave
        
        ports:
        
        - containerPort: 5000
