apiVersion: apps/v1
containers: 
  - 
    name: myapp
image: harishoo7/glams
kind: Deployment
labels: ~
matchLabels: ~
metadata: ~
name: myapp
ports: 
  - 
    containerPort: 5000
replicas: 1
run: myapp
selector: ~
spec: ~
template: ~
