apiVersion: apps/v1

kind: Deployment

metadata:

  name: harish
  
  namespace: dev 
  
spec:

  selector:
  
    matchLabels:
    
      run: harish
      
  replicas: 1
  
  template:
    
    metadata:
    
      labels:
      
        run: harish
        
    spec:
      
      containers:
      
      - name: harish
      
        image: harishoo7/harish
        
        ports:
        
        - containerPort: 5000
