apiVersion: v1
kind: Service
metadata: 
  name: myapp
  
  namespace: dev
  
  
  labels:
    run: myapp
spec:
  type: NodePort
  ports:
  - ports: 5000
    targetPort: 80
    protocol: TCP
    name: http
  
  selector:
    run: myapp
